# If you do not have OpenSSL installed, update
# the following line to use "http://" instead
source 'https://rubygems.org'

gem "middleman"

# Live-reloading plugin
gem "middleman-livereload"
# gem 'middleman-deploy', '~> 1.0'

# For faster file watcher updates on Windows:
gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]

# Windows does not come with time zone data
gem "tzinfo-data", platforms: [:mswin, :mingw]

gem "slim"
gem "bootstrap-sass", :require => false
