StaticData = {
  bodyNames: {
   "sedan"        =>"sedan",
   "sedan_long"   =>"sedan long",
   "wagon"        =>"wagon",
   "hatch_3d"     =>"hatch 3d",
   "hatch_5d"     =>"hatch 5d",
   "suv"          =>"SUV",
   "suv_2d"       =>"SUV 2-dr",
   "suv_3d"       =>"SUV 3-dr",
   "suv_4d"       =>"SUV 4-dr",
   "suv_5d"       =>"SUV 5-dr",
   "cabrio"       =>"cabriolet",
   "coupe"        =>"coupe",
   "coupe_2d"     =>"coupe 2-dr",
   "coupe_5d"     =>"coupe 5-dr",
   "crossover"    =>"crossover",
   "crossover_3d" =>"crossover 3-dr",
   "crossover_5d" =>"crossover 5-dr",
   "minivan"      =>"minivan",
   "minivan_3d"   =>"minivan 3-dr",
   "minivan_5d"   =>"minivan 5-dr",
   "van"          =>"van",
   "pickup"       =>"pickup",
   "pickup_2d"    =>"pickup 2-dr",
   "pickup_4d"    =>"pickup 4-dr",
  },
  premiumBrandKeys: %w(mercedes_benz audi bmw lexus infinity acura volvo cadillac range_rover),
  parameterGroups: [:engine, :dimensions, :other],
  parameterGroupsData: {
    engine: ["Engine", [:acceleration_100kmh, :top_speed, :max_power, :max_power_kw, :max_torque, :displacement, :cylinder_count, :cylinder_valves, :compression, :bore, :gears, :consumption_city, :consumption_highway, :consumption_mixed]],
    dimensions: ["Dimensions", [:length, :width, :height, :ground_clearance, :wheelbase, :kerbweight, :gross_mass, :tires, :front_tire_rut, :rear_tire_rut, :luggage_min, :luggage_max, :tank_capacity, :doors, :seats_min, :seats_max]],
    other: ["Other", [:produced_since, :produced_till]]
  },
  parameterNames: {
    top_speed:              "Top Speed",
    acceleration_100kmh: "Acelleration (0-100 km/h)",
    consumption_city:       "Consumption (city)",
    consumption_highway:    "Consumption (highway)",
    consumption_mixed:      "Consumption (mixed)",
    displacement:          "Displacement",
    cylinder_count:         "Cylider Count",
    cylinder_valves:    "Valves per Cylider",
    compression:            "Compression",
    bore:                   "Bore",
    max_power:              "Power (hp)",
    max_power_kw:           "Power (kW)",
    max_torque:             "Torque",
    # max_power_range_start: :value,
    # max_torque_range_start: :value,
    gears:                  "Gears Number",
    length:                 "Length",
    width:                  "Width",
    height:                 "Height",
    ground_clearance:       "Ground Clearance",
    tires:                  "Tires",
    front_tire_rut:         "Front Tire Rut",
    rear_tire_rut:          "Rear Tire Rut",
    wheelbase:              "Wheelbase",
    luggage_min:            "Luggage (min)",
    luggage_max:            "Luggage (max)",
    tank_capacity:          "Tank Capacity",
    kerbweight:             "Kerb Weight",
    gross_mass:             "Gross Weight",
    doors:                  "Doors Count",
    seats_min:              "Seats (min)",
    seats_max:              "Seats (max)",
    produced_since:         "Produced Since",
    produced_till:          "Produced Till",
  },
  parameterUnits: {
    top_speed: :kmh,
    acceleration_100kmh: :s,
    consumption_city: :l100km,
    consumption_highway: :l100km,
    consumption_mixed: :l100km,
    displacement: :cc,
    cylinder_count: :count,
    cylinder_valves: :count,
    compression: :value,
    bore: :mm,
    max_power: :hp,
    max_power_kw: :kw,
    max_power_range_start: :value,
    max_torque: :nm,
    max_torque_range_start: :value,
    gears: :count,
    length: :mm,
    width: :mm,
    height: :mm,
    ground_clearance: :mm,
    tires: :tires,
    front_tire_rut: :mm,
    rear_tire_rut: :mm,
    wheelbase: :mm,
    luggage_min: :l,
    luggage_max: :l,
    tank_capacity: :l,
    gross_mass: :kg,
    kerbweight: :kg,
    doors: :count,
    seats_min: :count,
    seats_max: :count,
    produced_since: :date,
    produced_till: :date,
    price: :usd,
  },
  parameterUnitNames: {
    kmh:    "km/h",
    s:      "s",
    l100km: "l/100km",
    cc:     "cc",
    count:  "",
    value:  "",
    mm:     "mm",
    hp:     "hp",
    kw:     "kW",
    nm:     "Nm",
    tires:  "",
    l:      "l",
    kg:     "kg",
    date:   "",
    rouble: "",  
  },
  categoryNames: {
     A: ["City (A class)", "City"],
     B: ["Supermini (B class)", "Supermini"],
     C: ["Compact (C/Golf class)", "Compacts"],
     D: ["Family (D class)", "Family"],
     E: ["Business (E class)", "Business"],
     F: ["Premium Sedans", "Premium"],
    Xb: ["Very Compact SUVs"],
    Xc: ["Compact SUVs"],
    Xd: ["Compact+ SUVs"],
    Xe: ["Mid-Size SUVs"],
    Xf: ["Full-Size SUVs"],
    Xx: ["Offroad SUVs"],
    Wx: ["AWD Wagons"],
    Sr: ["Roadsters"],
    Sc: ["Sportcars"],
    Mb: ["Mini MPVs"],
    Mc: ["Compact MPVs"],
    Me: ["Mid-Size MPVs"],
    Pc: ["Compact Pickups"],
    Pd: ["Full-Size Pickups"],  
  },
  brandNames: {
		acura:         "Acura",
		alfa_romeo:    "Alfa Romeo",
		audi:          "Audi",
		bmw:           "BMW",
		cadillac:      "Cadillac",
		chery:         "Chery",
		chevrolet:     "Chevrolet",
		chrysler:      "Chrysler",
		citroen:       "Citroen",
		daewoo:        "Daewoo",
		dodge:         "Dodge",
		fiat:          "FIAT",
		ford:          "Ford",
		gaz:           "GAZ",
		great_wall:    "Great Wall",
		honda:         "Honda",
		hummer:        "Hummer",
		hyundai:       "Hyundai",
		infiniti:      "Infiniti",
		jaguar:        "Jaguar",
		jeep:          "Jeep",
		kia:           "Kia",
		land_rover:    "Land Rover",
		lexus:         "Lexus",
		mazda:         "Mazda",
		mercedes_benz: "Mercedes-Benz",
		mini:          "MINI",
		mitsubishi:    "Mitsubishi",
		nissan:        "Nissan",
		opel:          "Opel",
		peugeot:       "Peugeot",
		porsche:       "Porsche",
		renault:       "Renault",
		saab:          "Saab",
		seat:          "SEAT",
		skoda:         "Skoda",
		ssangyong:     "SsangYong",
		subaru:        "Subaru",
		suzuki:        "Suzuki",
		toyota:        "Toyota",
		uaz:           "UAZ",
		vaz:           "VAZ (LADA)",
		volkswagen:    "Volkswagen",
		volvo:         "Volvo",
	},  
  chartColors: {
    top_speed:              [  0, 75, 50],
    acceleration_100kmh: [ 30, 75, 50],
    consumption_city:       [ 60, 75, 50],
    consumption_highway:    [ 90, 75, 50], 
    consumption_mixed:      [120, 75, 50],
    displacement:          [150, 75, 50],
    cylinder_count:         [180, 75, 50],
    cylinder_valves:    [210, 75, 50],
    compression:            [240, 75, 50],
    bore:                   [270, 75, 50],
    max_power:              [300, 75, 50],
    max_power_kw:           [330, 75, 50],
    max_torque:             [360, 75, 50],
    gears:                  [  0, 50, 50],
    length:                 [ 30, 50, 50],
    width:                  [ 60, 50, 50],
    height:                 [ 90, 50, 50],
    ground_clearance:       [120, 50, 50],
    tires:                  [150, 50, 50],
    front_tire_rut:         [180, 50, 50],
    rear_tire_rut:          [210, 50, 50],
    wheelbase:              [240, 50, 50],
    luggage_min:            [270, 50, 50],
    luggage_max:            [300, 50, 50],
    tank_capacity:          [330, 50, 50],
    gross_mass:             [360, 50, 50],
    kerbweight:             [  0, 50, 50],
    doors:                  [ 30, 50, 50],
    seats_min:              [ 60, 50, 50],
    seats_max:              [ 90, 50, 50],
    produced_since:         [120, 50, 50],
    price:                  [140, 50, 50],
  },
  colors: [
    [  0, 75, 70],
    [240, 75, 70],
    [120, 75, 70],
    [ 30, 75, 70],
    [270, 75, 70],
    [ 60, 75, 70],
    [210, 75, 70],
    [300, 75, 70],
    [ 90, 75, 70],    
    [330, 50, 50],
    [ 60, 50, 50],
    [240, 50, 50],
    [ 90, 50, 50],
  ],
  sampleModSets: {
    business: [
      "bmw 5 2010 sedan 2.5i-204ps-AT-RWD",
      "bmw 5 2010 sedan 3.0i-258ps-AT-RWD",
      "bmw 5 2010 sedan 3.0i-306ps-AT-RWD",
      "citroen c6 2005 sedan 2.9i-211ps-AT-FWD",
      "infiniti m 2010 sedan 2.5i-222ps-AT-RWD",
      "infiniti m 2010 sedan 3.7i-333ps-AT-4WD",
      "lexus es 2009 sedan 2.4i-165ps-AT-FWD",
      "lexus es 2009 sedan 3.5i-275ps-AT-FWD",
      "lexus gs 2012 sedan 2.5i-209ps-AT-RWD",
      "lexus gs 2012 sedan 3.5i-317ps-AT-4WD",
      "mercedes_benz e 2009 sedan 1.8i-204ps-AT-RWD",
      "mercedes_benz e 2009 sedan 3.0i-231ps-AT-RWD",
      "mercedes_benz e 2009 sedan 3.5i-252ps-AT-RWD",
      "volvo s80 2010 sedan 2.5i-231ps-AT-FWD",
      "volvo s80 2010 sedan 3.2i-243ps-AT-4WD",
      "chrysler 300c 2011 sedan 3.6i-292ps-AT-RWD",
      "peugeot 607 2005-2010 sedan 2.9i-211ps-AT-FWD",
      "peugeot 607 2005-2010 sedan 2.2i-158ps-AT-FWD",
      "honda legend 2008-2011 sedan 3.7i-295ps-AT-4WD",
      "cadillac sts 2007 sedan 3.6i-257ps-AT-RWD",  
    ],
    compact: [
      "chevrolet cruze 2009 sedan 1.8i-141ps-AT-FWD",
      "citroen c4 2011 hatch_5d 1.6i-120ps-AT-FWD",
      "ford focus 2011 sedan 2.0i-150ps-AMT-FWD",
      "honda civic 2012 sedan 1.8i-142ps-AT-FWD",
      "hyundai i30 2012 hatch_5d 1.6i-130ps-AT-FWD",
      "mitsubishi lancer 2007 sedan 2.0i-150ps-CVT-4WD",
      "mitsubishi lancer 2007 sedan 2.0i-150ps-CVT-FWD",
      "opel astra 2010 hatch_5d 1.6i-180ps-AT-FWD",
      "opel astra 2010 hatch_5d 1.4i-140ps-AT-FWD",
      "subaru impreza 2007 sedan 2.0i-150ps-AT-4WD",
      "subaru impreza 2007 sedan 1.5i-107ps-AT-4WD",
      "toyota corolla 2010 sedan 1.6i-124ps-AT-FWD",
      "volkswagen jetta 2011 sedan 1.4i-150ps-AMT-FWD",
      "volkswagen jetta 2011 sedan 1.4i-122ps-AMT-FWD",
      "volkswagen jetta 2011 sedan 1.6i-105ps-AT-FWD",
      "volvo s40 2007 sedan 2.5i-230ps-AT-4WD",
      "volvo s40 2007 sedan 2.0i-145ps-AMT-FWD",
      "volvo s40 2007 sedan 2.4i-140ps-AT-FWD",
      "renault fluence 2010 sedan 1.6i-106ps-AT-FWD",
      "skoda octavia 2008 hatch_5d 1.8i-152ps-AT-FWD",
      "skoda octavia 2008 hatch_5d 1.6i-102ps-AT-FWD",
      "skoda octavia 2008 hatch_5d 1.4i-122ps-AMT-FWD",
    ],
    midSuvs: [
      "bmw x5 2010 crossover 3.0i-306ps-AT-4WD",
      "bmw x5 2010 crossover 4.4i-407ps-AT-4WD",
      "bmw x5 2010 crossover 3.0d-245ps-AT-4WD",
      "bmw x6 2008 crossover 3.0i-306ps-AT-4WD",
      "honda pilot 2011 suv 3.5i-249ps-AT-4WD",
      "hummer h3 2005-2010 suv 3.7i-242ps-AT-4WD",
      "hyundai ix55 2009 suv 3.8i-264ps-AT-4WD",
      "infiniti fx 2012 crossover 3.0d-238ps-AT-4WD",
      "infiniti fx 2012 crossover 5.0i-400ps-AT-4WD",
      "infiniti fx 2012 crossover 3.7i-333ps-AT-4WD",
      "land_rover discovery 2009 suv 3.0d-245ps-AT-4WD",
      "land_rover discovery 2009 suv 2.7d-190ps-AT-4WD",
      "land_rover range_rover_sport 2009 suv 3.0d-245ps-AT-4WD",
      "land_rover range_rover_sport 2009 suv 5.0i-375ps-AT-4WD",
      "mazda cx_9 2007-2009 crossover 3.7i-277ps-AT-4WD",
      "lexus rx 2009 suv 2.7i-188ps-AT-FWD",
      "lexus rx 2009 suv 3.5i-249ps-CVT-4WD",
      "mercedes_benz m 2011 suv 2.1d-204ps-AT-4WD",
      "mercedes_benz m 2011 suv 3.0d-258ps-AT-4WD",
      "mercedes_benz m 2011 suv 3.5i-306ps-AT-4WD",
      "mitsubishi pajero 2011 suv 3.0i-178ps-AT-4WD",
      "mitsubishi pajero 2011 suv 3.2d-200ps-AT-4WD",
      "mitsubishi pajero 2011 suv 3.8i-250ps-AT-4WD",
      "nissan murano 2008 crossover 3.5i-249ps-CVT-4WD",
      "porsche cayenne 2010 suv 3.0d-240ps-AT-4WD",
      "porsche cayenne 2010 suv 3.0i-380ps-AT-4WD",
      "porsche cayenne 2010 suv 4.8i-400ps-AT-4WD",
      "subaru tribeca 2007 suv 3.6i-258ps-AT-4WD",
      "volkswagen touareg 2010 suv 3.0d-240ps-AT-4WD",
      "volkswagen touareg 2010 suv 3.0i-333ps-AT-4WD",
      "volkswagen touareg 2010 suv 3.6i-249ps-AT-4WD",
      "volkswagen touareg 2010 suv 3.0d-204ps-AT-4WD",
      "volvo xc90 2006 crossover 2.4d-185ps-AT-4WD",
      "volvo xc90 2006 crossover 3.2i-243ps-AT-4WD",      
    ]
  }
}
