ParameterNames = {
  top_speed: "Top Speed",
  acceleration_0_100_kmh: "Acelleration",
  consumption_city: "Consumption (city)",
  consumption_highway: "Consumption (highway)",
  consumption_mixed: "Consumption (mixed)",
  engine_volume: "Displacement",
  cylinder_count: "Cyliders",
  valves_per_cylinder: "Valves per Cylider",
  compression: "Compression",
  bore: "Bore",
  max_power: "Power",
  max_power_kw: "Power, kW",
  # max_power_range_start: :value,
  max_torque: "Torque",
  # max_torque_range_start: :value,
  gears: "Gears",
  length: "Length",
  width: "Width",
  height: "Height",
  ground_clearance: "Ground Clearance",
  tires: "Tires",
  front_tire_rut: :mm,
  rear_tire_rut: :mm,
  wheelbase: "Wheelbase",
  luggage_min: "Luggage (min)",
  luggage_max: "Luggage (max)",
  tank_capacity: "Tank Capacity",
  gross_mass: "Gross Weight",
  kerbweight: "Kerb Weight",
  doors: "Doors Count",
  seats: "Seats Count",
  produced_since: "Produced Since",
  price: "Price",
}

ParameterUnits = {
  top_speed: :kmh,
  acceleration_0_100_kmh: :s,
  consumption_city: :l100km,
  consumption_highway: :l100km,
  consumption_mixed: :l100km,
  engine_volume: :cc,
  cylinder_count: :count,
  valves_per_cylinder: :count,
  compression: :value,
  bore: :mm,
  max_power: :ps,
  max_power_kw: :kw,
  max_power_range_start: :value,
  max_torque: :nm,
  max_torque_range_start: :value,
  gears: :count,
  length: :mm,
  width: :mm,
  height: :mm,
  ground_clearance: :mm,
  tires: :tires,
  front_tire_rut: :mm,
  rear_tire_rut: :mm,
  wheelbase: :mm,
  luggage_min: :l,
  luggage_max: :l,
  tank_capacity: :l,
  gross_mass: :kg,
  kerbweight: :kg,
  doors: :count,
  seats: :count,
  produced_since: :date,
  price: :rouble,
}

ParameterUnitNames = {
  kmh: "km/h",
  s: "s",
  l100km: "l/100km",
  cc: "cc",
  count: "",
  value: "",
  mm: "mm",
  ps: "ps",
  kw: "kw",
  nm: "Nm",
  tires: "",
  l: "l",
  kg: "kg",
  date: "",
  rouble: "",  
}
