ParameterUnits = {
  top_speed: :kmh,
  acceleration_0_100_kmh: :s,
  consumption_city: :l100km,
  consumption_highway: :l100km,
  consumption_mixed: :l100km,
  engine_volume: :cc,
  cylinder_count: :count,
  valves_per_cylinder: :count,
  compression: :value,
  bore: :mm,
  max_power: :ps,
  max_power_kw: :kw,
  max_power_range_start: :value,
  max_torque: :nm,
  max_torque_range_start: :value,
  gears: :count,
  length: :mm,
  width: :mm,
  height: :mm,
  ground_clearance: :mm,
  tires: :tires,
  front_tire_rut: :mm,
  rear_tire_rut: :mm,
  wheelbase: :mm,
  luggage_min: :l,
  luggage_max: :l,
  tank_capacity: :l,
  gross_mass: :kg,
  kerbweight: :kg,
  doors: :count,
  seats: :count,
  produced_since: :date,
  price: :rouble,
}

ParameterUnitNames = {
  kmh: "km/h",
  s: "sec",
  l100km: "l/100km",
  cc: "cc",
  count: "",
  value: "",
  mm: "mm",
  ps: "ps",
  kw: "kw",
  nm: "Nm",
  tires: "",
  l: "l",
  kg: "kg",
  date: "",
  rouble: "",  
}
